name: Publish
on:
    schedule:
        - cron: "0 0 * * 1,5"
    workflow_dispatch:
        inputs:
            push-registry:
                description: 'Push to the Registry'
                type: boolean
                required: true
                default: true
    push:
        branches: [main]
        paths:
            - '**/Dockerfile'
concurrency:
    group: ${{ github.repository }}
    cancel-in-progress: true

jobs:
    image:
        name: 'Image'
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        env:
            REGISTRY: ghcr.io
            IMAGE_NAME: ${{ github.repository }}
            PUSH_REGISTRY: true
        strategy:
            fail-fast: false
            matrix:
                release:
                    - tags: latest, latest-bookworm-slim
                      base: mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim
                      branch: latest
                    - tags: stg-bookworm-slim
                      base: mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim
                      branch: stg
                    - tags: latest-alpine
                      base: mcr.microsoft.com/dotnet/sdk:8.0-alpine
                      branch: latest
                    - tags: stg-alpine
                      base: mcr.microsoft.com/dotnet/sdk:8.0-alpine
                      branch: stg
        steps:
            - name: Set Up
              uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25 # v3
            - name: Docker Buildx
              uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            - name: Determine whether to push to registry
              run: |
                  if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
                     echo "PUSH_REGISTRY=${{ github.event.inputs.push-registry }}" >> $GITHUB_ENV
                  else
                    echo "PUSH_REGISTRY=true" >> $GITHUB_ENV
                  fi
            - name: Login to container registry
              uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
              with:
                registry: ${{ env.REGISTRY }}     
                username: ${{ github.actor }}
                password: ${{ secrets. GITHUB_TOKEN }}
                logout: true
            - name: Extract Metadata
              id: meta
              uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                tags: ${{ matrix.release.tags }}
            - name: Build & Publish
              uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497 # v6
              with:
                context: .
                push: ${{ env.PUSH_REGISTRY }}
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outcome.labels }}
                platforms: linux/amd64, linux/arm64
                build-args: |
                    OS=${{ matrix.release.base }}
                    DALAMUD_BRANCH=${{ matrix.release.branch }}
    cleanup:
        name: "Cleanup"
        runs-on: ubuntu-latest
        needs: [image]
        permissions:
            contents: read
            packages: write
        steps:
            - name: Prune Untagged
              uses: vlaurin/action-ghcr-prune@0cf7d39f88546edd31965acba78cdcb0be14d641 # v0.6.0
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                container: docker
                keep-younger-than: 7
                prune-untagged: true          